"""add exam processing fields

Revision ID: 5badfee1f859
Revises: 66de03868a44
Create Date: 2026-03-02 13:20:31.485281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5badfee1f859'
down_revision = '66de03868a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='PENDING', nullable=False))
        batch_op.add_column(sa.Column('model_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.drop_column('error_message')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('model_version')
        batch_op.drop_column('model_name')
        batch_op.drop_column('status')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
