"""cascade delete exame

Revision ID: 66de03868a44
Revises: de29970b2967
Create Date: 2026-02-23 23:31:12.719805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66de03868a44'
down_revision = 'de29970b2967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('exame_paciente_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'paciente', ['paciente_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('exame_paciente_id_fkey'), 'paciente', ['paciente_id'], ['id'])

    # ### end Alembic commands ###
