"""add processing_time

Revision ID: 672560f685e0
Revises: 5badfee1f859
Create Date: 2026-03-30 02:45:53.376403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '672560f685e0'
down_revision = '5badfee1f859'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processing_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exame', schema=None) as batch_op:
        batch_op.drop_column('processing_time')

    # ### end Alembic commands ###
